test:
  adapter: sqlite3
  database: the99names_dev
  pool: 5
  timeout: 5000000000

development:
  adapter: postgresql
  database: the99names
  username: t9n
  password: the99names
  host: 162.243.207.15
  port: 5432
  pool: 5
  timeout: 90000
